name: my_responsive_ui
description: A Flutter package for creating responsive UIs with easy to use extensions and utilities.
version: 1.0.3+1
homepage: https://github.com/samandarsharifjonov/my_responsive_ui

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



